<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="467" started-at="2021-06-04T03:30:31 EDT" finished-at="2021-06-04T03:30:31 EDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="467" started-at="2021-06-04T03:30:31 EDT" finished-at="2021-06-04T03:30:31 EDT">
      <class name="ExtentTestReport">
        <test-method status="PASS" signature="startTest()[pri:0, instance:ExtentTestReport@2758fe70]" name="startTest" is-config="true" duration-ms="164" started-at="2021-06-04T03:30:31 EDT" finished-at="2021-06-04T03:30:31 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method status="PASS" signature="verifyPageTitle()[pri:0, instance:ExtentTestReport@2758fe70]" name="verifyPageTitle" duration-ms="10" started-at="2021-06-04T03:30:31 EDT" finished-at="2021-06-04T03:30:31 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPageTitle -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:ExtentTestReport@2758fe70]" name="getResult" is-config="true" duration-ms="1" started-at="2021-06-04T03:30:31 EDT" finished-at="2021-06-04T03:30:31 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyPageTitle status=SUCCESS method=ExtentTestReport.verifyPageTitle()[pri:0, instance:ExtentTestReport@2758fe70] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="verifyPageUrl()[pri:0, instance:ExtentTestReport@2758fe70]" name="verifyPageUrl" duration-ms="2" started-at="2021-06-04T03:30:31 EDT" finished-at="2021-06-04T03:30:31 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Google.com] but found [Yahoo.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Google.com] but found [Yahoo.com]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at ExtentTestReport.verifyPageUrl(ExtentTestReport.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPageUrl -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:ExtentTestReport@2758fe70]" name="endTest" is-config="true" duration-ms="257" started-at="2021-06-04T03:30:31 EDT" finished-at="2021-06-04T03:30:31 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:ExtentTestReport@2758fe70]" name="getResult" is-config="true" duration-ms="0" started-at="2021-06-04T03:30:31 EDT" finished-at="2021-06-04T03:30:31 EDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyPageUrl status=FAILURE method=ExtentTestReport.verifyPageUrl()[pri:0, instance:ExtentTestReport@2758fe70] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
      </class> <!-- ExtentTestReport -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
